SELECT DISTINCT 
  CUSTOMERID,CUSTNAME, CNIC,NTN,
  -- ORGNAME, 
 ADDRESS,         
  REGIONNAME, 
  SUM(GROSS_AMT) AS GROSS_AMT,
   SUM(DISCOUNT_AMT) AS DISCOUNT_AMT, 
  SUM(NET_AMT)  AS NET_AMT,
  TAX_P
  ,  ROUND(SUM(NET_AMT*NVL(TAX_P,0)/100),2) ADV_TAX
  ,proprietor 
  FROM(
SELECT DISTINCT 
  CUSTOMERID,
CUSTNAME, CNIC,NTN,
  -- ORGNAME, 
 ADDRESS,              
  REGIONNAME, 
  SUM(GROSS_AMT) AS GROSS_AMT,
   SUM(DISCOUNT_AMT) AS DISCOUNT_AMT, 
  SUM(NET_AMT)  AS NET_AMT,
  NVL(MIN(TAX_P),0) TAX_P
  --,  ROUND(SUM(NET_AMT*NVL(TAX_P,0)/100),2) ADV_TAX
  ,proprietor 
  FROM
(SELECT DISTINCT 
  SALE_MASTER.CUSTOMERID,
  CUSTOMERS.CNIC,CUSTOMERS.NTN,
  CUSTOMERS.ORGNAME CUSTNAME, 
  CUSTOMERS.proprietor,
  SALE_MASTER.CUSTOMERID||' - '||CUSTOMERS.ORGNAME AS ORGNAME, 
  CUSTOMERS.ADDRESS,
  SALE_MASTER.TRANSNO, 
  SALE_MASTER.TRANSDATE, 
  REGION.REGIONNAME, 
  SALE_DETAIL.COMPANY_ID, 
  SALE_DETAIL.COMPANY_ID||' - '||COMPANY.COMPANY_NAME AS COMPANYNAME, 
  PRODUCTS.GROUPID, 
  PRODUCTS.GROUPID||' - '||COMPGROUPS.GROUPNAME AS GROUPNAME, 
  SALE_DETAIL.PRODUCTID, 
  PRODUCTS.PRODNAME AS PRODNAME, 
  PRODUCTS.UNIT, 
  PRODUCTS.UNITPRICE,
  SUM(SALE_DETAIL.GROSS_AMT) AS GROSS_AMT,
  SUM(SALE_DETAIL.SALE_QTY)AS SALE_QTY, 
  SUM(SALE_DETAIL.BONUS_QTY)AS BONUS_QTY, 
  SALE_DETAIL.DISCOUNT_P,
  SUM(SALE_DETAIL.DISCOUNT_AMT) AS DISCOUNT_AMT, 
  SUM(SALE_DETAIL.NET_AMT) AS NET_AMT,SALE_MASTER.TAX_P
FROM COMPANY, COMPGROUPS, CUSTOMERS, PRODUCTS, SALE_MASTER, SALE_DETAIL, REGION
WHERE ((SALE_MASTER.CUSTOMERID = CUSTOMERS.CUSTOMERID
  AND SALE_MASTER.UNITNO = CUSTOMERS.UNITNO
  AND SALE_MASTER.COMPCODE = CUSTOMERS.COMPCODE)
  AND (SALE_DETAIL.TRANSTYPE = SALE_MASTER.TRANSTYPE
  AND SALE_DETAIL.TRANSDATE = SALE_MASTER.TRANSDATE
  AND SALE_DETAIL.TRANSNO = SALE_MASTER.TRANSNO
  AND SALE_DETAIL.UNITNO = SALE_MASTER.UNITNO
  AND SALE_DETAIL.COMPCODE = SALE_MASTER.COMPCODE)
  AND (CUSTOMERS.REGIONID = REGION.REGIONID)
  AND (SALE_DETAIL.COMPCODE = COMPANY.COMPCODE)
  AND (SALE_DETAIL.UNITNO = COMPANY.UNITNO)
  AND (SALE_DETAIL.COMPANY_ID = COMPANY.COMPANY_ID)
  AND (SALE_DETAIL.COMPCODE = PRODUCTS.COMPCODE)
  AND (SALE_DETAIL.UNITNO = PRODUCTS.UNITNO)
  AND (SALE_DETAIL.COMPANY_ID = PRODUCTS.COMPANY_ID)
  AND (SALE_DETAIL.PRODUCTID = PRODUCTS.PRODUCTID)
  AND (COMPGROUPS.COMPCODE = PRODUCTS.COMPCODE)
  AND (COMPGROUPS.UNITNO = PRODUCTS.UNITNO)
  AND (COMPGROUPS.COMPNAY_ID = PRODUCTS.COMPANY_ID)
  AND (COMPGROUPS.GROUPID = PRODUCTS.GROUPID)) 
  AND SALE_MASTER.TRANSTYPE = 'S'
  AND SALE_MASTER.TRANSDATE BETWEEN &F_DATE AND &T_DATE
  AND COMPANY.MID=&MID
               
GROUP BY SALE_MASTER.CUSTOMERID,CUSTOMERS.CNIC,CUSTOMERS.NTN,CUSTOMERS.ORGNAME,CUSTOMERS.ADDRESS,
           CUSTOMERS.proprietor,SALE_MASTER.TRANSNO,SALE_MASTER.TRANSDATE,REGION.REGIONNAME,SALE_DETAIL.COMPANY_ID, 
         COMPANY.COMPANY_NAME,PRODUCTS.GROUPID,COMPGROUPS.GROUPNAME,SALE_DETAIL.PRODUCTID, 
         PRODUCTS.PRODNAME,SALE_DETAIL.DISCOUNT_P,PRODUCTS.UNIT,PRODUCTS.UNITPRICE,SALE_MASTER.TAX_P 
UNION ALL
SELECT DISTINCT 
  RETURN_MASTER.CUSTOMERID,  
  CUSTOMERS.CNIC,CUSTOMERS.NTN,
CUSTOMERS.ORGNAME CUSTNAME,
  CUSTOMERS.proprietor, 
  RETURN_MASTER.CUSTOMERID||' - '||CUSTOMERS.ORGNAME AS ORGNAME, 
               CUSTOMERS.ADDRESS,
                RETURN_MASTER.TRANSNO, 
               RETURN_MASTER.TRANSDATE,
  REGION.REGIONNAME, 
  RETURN_DETAIL.COMPANY_ID, 
  RETURN_DETAIL.COMPANY_ID||' - '||COMPANY.COMPANY_NAME AS COMPANYNAME, 
  PRODUCTS.GROUPID, 
  PRODUCTS.GROUPID||' - '||COMPGROUPS.GROUPNAME AS GROUPNAME, 
  RETURN_DETAIL.PRODUCTID, 
  PRODUCTS.PRODNAME AS PRODNAME, 
  PRODUCTS.UNIT, 
  PRODUCTS.UNITPRICE,
SUM(RETURN_DETAIL.GROSS_AMT-
                        (RETURN_DETAIL.GROSS_AMT-(RETURN_DETAIL.GROSS_AMT*NVL(RETURN_MASTER.TAX_P,0)/100) )
                         *NVL(RETURN_MASTER.TAX_P,0)/100
)
* -1 AS GROSS_AMT,
  SUM(RETURN_DETAIL.SALE_QTY )* -1 AS SALE_QTY, 
  SUM(RETURN_DETAIL.BONUS_QTY )* -1 AS BONUS_QTY, 
  RETURN_DETAIL.DISCOUNT_P,
  --SUM(RETURN_DETAIL.DISCOUNT_AMT ) * -1 AS DISCOUNT_AMT, 
SUM(RETURN_DETAIL.DISCOUNT_AMT-
                        (RETURN_DETAIL.DISCOUNT_AMT-(RETURN_DETAIL.DISCOUNT_AMT*NVL(RETURN_MASTER.TAX_P,0)/100) )
                         *NVL(RETURN_MASTER.TAX_P,0)/100
)
* -1 AS DISCOUNT_AMT,
SUM(RETURN_DETAIL.NET_AMT-
                        (RETURN_DETAIL.NET_AMT-(RETURN_DETAIL.NET_AMT*NVL(RETURN_MASTER.TAX_P,0)/100) )
                         *NVL(RETURN_MASTER.TAX_P,0)/100
)
* -1 AS NET_AMT,RETURN_MASTER.TAX_P

FROM COMPANY, COMPGROUPS, CUSTOMERS, PRODUCTS, RETURN_MASTER, RETURN_DETAIL, REGION
WHERE ((RETURN_MASTER.CUSTOMERID = CUSTOMERS.CUSTOMERID
  AND RETURN_MASTER.UNITNO = CUSTOMERS.UNITNO
  AND RETURN_MASTER.COMPCODE = CUSTOMERS.COMPCODE)
  AND (RETURN_DETAIL.TRANSTYPE = RETURN_MASTER.TRANSTYPE
  AND RETURN_DETAIL.TRANSDATE = RETURN_MASTER.TRANSDATE
  AND RETURN_DETAIL.TRANSNO = RETURN_MASTER.TRANSNO
  AND RETURN_DETAIL.UNITNO = RETURN_MASTER.UNITNO
  AND RETURN_DETAIL.COMPCODE = RETURN_MASTER.COMPCODE)
  AND (CUSTOMERS.REGIONID = REGION.REGIONID)
  AND (RETURN_DETAIL.COMPCODE = COMPANY.COMPCODE)
  AND (RETURN_DETAIL.UNITNO = COMPANY.UNITNO)
  AND (RETURN_DETAIL.COMPANY_ID = COMPANY.COMPANY_ID)
  AND (RETURN_DETAIL.COMPCODE = PRODUCTS.COMPCODE)
  AND (RETURN_DETAIL.UNITNO = PRODUCTS.UNITNO)
  AND (RETURN_DETAIL.COMPANY_ID = PRODUCTS.COMPANY_ID)
  AND (RETURN_DETAIL.PRODUCTID = PRODUCTS.PRODUCTID)
  AND (COMPGROUPS.COMPCODE = PRODUCTS.COMPCODE)
  AND (COMPGROUPS.UNITNO = PRODUCTS.UNITNO)
  AND (COMPGROUPS.COMPNAY_ID = PRODUCTS.COMPANY_ID)
  AND (COMPGROUPS.GROUPID = PRODUCTS.GROUPID)) 
  AND RETURN_MASTER.TRANSTYPE ='R'  
  AND RETURN_MASTER.TRANSDATE BETWEEN &F_DATE AND &T_DATE
  AND COMPANY.MID=&MID
GROUP BY RETURN_MASTER.CUSTOMERID, CUSTOMERS.CNIC,CUSTOMERS.NTN,
  CUSTOMERS.ORGNAME, CUSTOMERS.ADDRESS,  CUSTOMERS.proprietor,RETURN_MASTER.TRANSNO,RETURN_MASTER.TRANSDATE,
  REGION.REGIONNAME,RETURN_DETAIL.COMPANY_ID,COMPANY.COMPANY_NAME,PRODUCTS.GROUPID, 
  COMPGROUPS.GROUPNAME,RETURN_DETAIL.PRODUCTID,PRODUCTS.PRODNAME,RETURN_DETAIL.DISCOUNT_P,
  PRODUCTS.UNIT,PRODUCTS.UNITPRICE,RETURN_MASTER.TAX_P)
GROUP BY CUSTOMERID, CNIC,NTN,CUSTNAME,ORGNAME,ADDRESS,REGIONNAME--,NVL(TAX_P,0)
, proprietor)
GROUP BY CUSTOMERID, CNIC,NTN,CUSTNAME,ADDRESS,REGIONNAME,TAX_P, proprietor
ORDER BY 1,4,5
