SELECT 
DSS_MASTER.DSS_NO, 
DSS_MASTER.DSS_DATE, 
DSS_MASTER.DELMANID, 
'   ' ||DSS_MASTER.DELMANID|| ' - ' ||EMPLOYEE.FIRSTNAME AS FIRSTNAME, 
ROUND(SUM(SD.NET_AMT)) AS DSS_AMOUNT , 
ROUND(SUM((SD.NET_AMT*NVL(SM.TAX_P,0)/100))) AS TAX_AMOUNT , 
ROUND(NVL(RTN.R_TAX_AMOUNT,0))  AS R_TAX_AMOUNT,
--SUM(DSS_DETAIL.CASH_AMT) AS CASH, 
0 AS CASH, 
ROUND(NVL(RTN.RETURN_AMT,0)-NVL(RTN.R_TAX_AMOUNT,0)) AS RETURN, 

ROUND(SUM(SD.NET_AMT)-ROUND(NVL(RTN.RETURN_AMT,0)-NVL(RTN.R_TAX_AMOUNT,0))) AS ACT_CASH,
--SUM(DSS_DETAIL.CREDIT_AMT) AS CREDIT, 
ROUND(NVL(SUM(SD.NET_AMT),0) -NVL(RTN.RETURN_AMT,0)-NVL(SUM(DSS_DETAIL.CASH_AMT) ,0) )AS CREDIT, 
DSS_MASTER.COLLECT_DATE AS COLLECT_DATE, 
DSS_MASTER.DSS_CLOSE AS DSS_STATUS
FROM DSS_MASTER, DSS_DETAIL, supply_man EMPLOYEE, SALE_MASTER SM, SALE_DETAIL SD, COMPANY CMPY
,
( SELECT UNITNO,COMPCODE, DSSNO, SUM(RETURN_AMT) RETURN_AMT, SUM(R_TAX_AMOUNT) AS R_TAX_AMOUNT  FROM
(SELECT RM.UNITNO,RM.COMPCODE, RM.DSSNO, SUM( RD.NET_AMT)
RETURN_AMT
,(SUM( RD.NET_AMT)-SUM( RD.NET_AMT*NVL(RM.TAX_P,0)/100))*NVL(RM.TAX_P,0)/100  AS R_TAX_AMOUNT 
FROM 
RETURN_MASTER RM,RETURN_DETAIL RD , COMPANY CMPY
WHERE  (RM.TRANSDATE = RD.TRANSDATE
 AND RM.TRANSNO = RD.TRANSNO
 AND RM.UNITNO = RD.UNITNO
 AND RM.COMPCODE = RD.COMPCODE)
 AND (RD.COMPANY_ID = CMPY.COMPANY_ID
 AND RD.UNITNO = CMPY.UNITNO
 AND RD.COMPCODE = CMPY.COMPCODE)
 --AND CMPY.MID =NVL(:MID,CMPY.MID)
 AND RM.DSSNO IN ( SELECT DISTINCT DSSM.DSS_NO FROM DSS_MASTER DSSM WHERE DSSM.DSS_DATE 
 BETWEEN '01-JUL-2021' AND '31-JUL-2021' )

 GROUP BY RM.UNITNO,RM.COMPCODE,RM.DSSNO,RM.TAX_P )
GROUP BY UNITNO,COMPCODE, DSSNO )
 RTN
 

WHERE ((DSS_DETAIL.DSS_DATE = DSS_MASTER.DSS_DATE
 AND DSS_DETAIL.DSS_NO = DSS_MASTER.DSS_NO
 AND DSS_DETAIL.UNITNO = DSS_MASTER.UNITNO
 AND DSS_DETAIL.COMPCODE = DSS_MASTER.COMPCODE)

 AND (DSS_DETAIL.TRANSDATE = SM.TRANSDATE
 AND DSS_DETAIL.TRANSNO = SM.TRANSNO
 AND DSS_DETAIL.UNITNO = SM.UNITNO
 AND DSS_DETAIL.COMPCODE = SM.COMPCODE)

 AND (SD.TRANSDATE = SM.TRANSDATE
 AND SD.TRANSNO = SM.TRANSNO
 AND SD.UNITNO = SM.UNITNO
 AND SD.COMPCODE = SM.COMPCODE)
 

AND (DSS_MASTER.DSS_NO = RTN.DSSNO(+)
 AND DSS_MASTER.UNITNO = RTN.UNITNO(+)
 AND DSS_MASTER.COMPCODE = RTN.COMPCODE(+))
 
 


 AND (SD.COMPANY_ID = CMPY.COMPANY_ID
 AND SD.UNITNO = CMPY.UNITNO
 AND SD.COMPCODE = CMPY.COMPCODE)

-- AND CMPY.MID =NVL(:MID,CMPY.MID)

 AND (DSS_MASTER.supply_man = EMPLOYEE.EMPLOYEEID(+))
 AND (DSS_MASTER.COMPCODE = EMPLOYEE.COMPCODE(+))
 AND (DSS_MASTER.UNITNO = EMPLOYEE.UNITNO(+))) 

 --AND DSS_MASTER.COMPCODE = :COMPCODE
 --AND DSS_MASTER.UNITNO = :UNITNO
--AND DSS_MASTER.DSS_NO BETWEEN NVL(:F_DSS,DSS_MASTER.DSS_NO) AND NVL(:T_DSS,DSS_MASTER.DSS_NO) 
 AND DSS_MASTER.DSS_DATE BETWEEN '01-JUL-2021' AND '31-JUL-2021'
-- AND DSS_MASTER.DSS_CLOSE = NVL(:STATUS,DSS_MASTER.DSS_CLOSE)
GROUP BY
DSS_MASTER.DSS_NO, 
DSS_MASTER.DSS_DATE, 
DSS_MASTER.DELMANID, 
EMPLOYEE.FIRSTNAME, 
DSS_MASTER.COLLECT_DATE, 
DSS_MASTER.DSS_CLOSE,
RTN.RETURN_AMT,
RTN.R_TAX_AMOUNT
ORDER BY 1;

