SELECT DISTINCT NVL(D.BOOKINGID,M.BOOKINGID) BOOKINGID,E.FIRSTNAME,D.COMPANY_ID||' - '||C.COMPANY_NAME COMPANY_NAME
,M.CUSTOMERID,CS.ORGNAME CUSTOMER
, COUNT(DISTINCT M.TRANSNO) INVOICES
FROM SALE_MASTER M,SALE_DETAIL D,COMPANY C,CUSTOMERS CS,EMPLOYEE E
  WHERE M.TRANSNO=D.TRANSNO
    AND D.COMPANY_ID=C.COMPANY_ID
    AND M.CUSTOMERID=CS.CUSTOMERID
    AND NVL(D.BOOKINGID,M.BOOKINGID)=E.EMPLOYEEID
    AND D.COMPANY_ID=&COMP
    --AND NVL(D.BOOKINGID,M.BOOKINGID)=&BOOKINGMAN
    AND M.TRANSDATE BETWEEN &F_DATE AND &T_DATE 
    GROUP BY NVL(D.BOOKINGID,M.BOOKINGID),E.FIRSTNAME,M.CUSTOMERID,D.COMPANY_ID,C.COMPANY_NAME,CS.ORGNAME
    ORDER BY 1,2,3;
