select * from sale_master where transdate=&T_DATE;
select 'Sale',ROUND(SUM(D.NET_AMT)+SUM(D.NET_AMT*M.TAX_P/100),2) AMT
 from SALE_MASTER M,SALE_DETAIL D
   WHERE M.TRANSNO=D.TRANSNO
    AND M.TRANSDATE =&T_DATE
    UNION ALL
    select 'Sale Return',ROUND(SUM(D.NET_AMT)+SUM(D.NET_AMT*M.TAX_P/100),2) AMT
 from RETURN_MASTER M,RETURN_DETAIL D
   WHERE M.TRANSNO=D.TRANSNO
    AND M.TRANSDATE =&T_DATE
    UNION ALL
    select 'Purchase',ROUND(SUM(D.NET_AMT),2) AMT
 from PURCHASE_MASTER M,PURCHASE_DETAIL D
   WHERE M.TRANSNO=D.TRANSNO
    AND M.TRANSDATE =&T_DATE
    AND M.TRANSTYPE='P'
    UNION ALL
    SELECT 'Cash Receipt',NVL(sum(AMOUNT),0) AMT
    FROM CASH_DETAIL 
    WHERE PAYMENT_TYPE='RECEIPTS' 
    AND TRANSDATE =&T_DATE
     UNION ALL
    SELECT 'Cash Payment',NVL(sum(AMOUNT),0) AMT
    FROM CASH_DETAIL 
    WHERE PAYMENT_TYPE='PAYMENTS'
        UNION ALL
    SELECT 'Bank Receipt',NVL(sum(AMOUNT),0) AMT
    FROM BANK_DETAIL 
    WHERE PAYMENT_TYPE='RECEIPTS' 
        AND TRANSDATE =&T_DATE
     UNION ALL
    SELECT 'Bank Payment',NVL(sum(AMOUNT),0) AMT
    FROM BANK_DETAIL 
    WHERE PAYMENT_TYPE='PAYMENTS'
        AND TRANSDATE =&T_DATE
     UNION ALL
    SELECT 'JV',NVL(sum(DR),0) AMT
    FROM JV_DETAIL 
    WHERE TRANSDATE =&T_DATE;

  --SELECT * FROM CASH_DETAIL;
