SELECT TRANSNO "VOUCHER #",TRANSDATE "VOUCHER DATE",'Discount' "VOUCHER DESCRIPTION",DEBIT,CREDIT
,SUM(DEBIT) OVER (order by TRANSDATE,TRANSNO) BALANCE FROM 
(SELECT 'SV-'||D.TRANSNO TRANSNO ,D.TRANSDATE,SUM(DISCOUNT_AMT) DEBIT,0 CREDIT
FROM SALE_DETAIL_LI D 
WHERE TRANSDATE >='01-JUL-2019'
--WHERE TRANSNO BETWEEN '278296' AND '278700'
GROUP BY D.TRANSNO,D.TRANSDATE
HAVING SUM(DISCOUNT_AMT)>0)
ORDER BY TRANSDATE,TRANSNO;


/*select 	sales_ts,
        sum(amount) over (order by sales_ts) 
from sales
*/
