SELECT CUSTOMERID,ORGNAME,ADDRESS,SUM(QTY) QTY FROM
(SELECT M.CUSTOMERID,C.ORGNAME,C.ADDRESS,SUM(D.SALE_QTY) QTY
FROM SALE_MASTER M,SALE_DETAIL D,CUSTOMERS C
 WHERE M.TRANSNO=D.TRANSNO
   AND M.CUSTOMERID=C.CUSTOMERID
   AND M.TRANSDATE BETWEEN &F_DATE AND &T_DATE
   AND D.COMPANY_ID=&COMP
   AND D.DISCOUNT_P>0
   GROUP BY M.CUSTOMERID,C.ORGNAME,C.ADDRESS
   UNION ALL
   SELECT M.CUSTOMERID,C.ORGNAME,C.ADDRESS,SUM(D.SALE_QTY)*-1 QTY 
FROM RETURN_MASTER M,RETURN_DETAIL D,CUSTOMERS C
 WHERE M.TRANSNO=D.TRANSNO
   AND M.CUSTOMERID=C.CUSTOMERID
   AND M.TRANSDATE BETWEEN &F_DATE AND &T_DATE
   AND D.COMPANY_ID=&COMP
   AND D.DISCOUNT_P>0
   GROUP BY M.CUSTOMERID,C.ORGNAME,C.ADDRESS)
   GROUP BY CUSTOMERID,ORGNAME,ADDRESS
   ORDER BY 1;
