SELECT * FROM (
WITH SAL AS(SELECT FY,CUSTOMERID,ORGNAME||' - '||ADDRESS CUSTOMERNAME,ORGNAME,ADDRESS,REGIONNAME,COMPPORD,COMPANY_ID,PRODUCTID,NOTE
,SUM(JAN) AS JAN,SUM(JANV) AS JANV
,SUM(FEB) AS FEB,SUM(FEBV) AS FEBV
,SUM(MAR) AS MAR,SUM(MARV) AS MARV
,SUM(APR) AS APR,SUM(APRV) AS APRV
,SUM(MAY) AS MAY,SUM(MAYV) AS MAYV
,SUM(JUN) AS JUN,SUM(JUNV) AS JUNV
,SUM(JUL) AS JUL,SUM(JULV) AS JULV
,SUM(AUG) AS AUG,SUM(AUGV) AS AUGV
,SUM(SEP) AS SEP,SUM(SEPV) AS SEPV
,SUM(OCT) AS OCT,SUM(OCTV) AS OCTV
,SUM(NOV) AS NOV,SUM(NOVV) AS NOVV
,SUM(DEC) AS DEC,SUM(DECV) AS DECV
FROM(
SELECT TO_CHAR(D.TRANSDATE,'YYYY') AS FY,M.CUSTOMERID,C.ORGNAME,C.ADDRESS,R.REGIONNAME,D.COMPPORD,D.COMPANY_ID,D.PRODUCTID,C.NOTE,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),01,SALE_QTY,0) AS JAN,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),01,D.SALE_QTY*P.UNITPRICE,0) AS JANV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),02,D.SALE_QTY,0) AS FEB,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),02,D.SALE_QTY*P.UNITPRICE,0) AS FEBV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),03,D.SALE_QTY,0) AS MAR,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),03,D.SALE_QTY*P.UNITPRICE,0) AS MARV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),04,D.SALE_QTY,0) AS APR,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),04,D.SALE_QTY*P.UNITPRICE,0) AS APRV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),05,D.SALE_QTY,0) AS MAY,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),05,D.SALE_QTY*D.UNIT_PRICE,0) AS MAYV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),06,D.SALE_QTY,0) AS JUN,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),06,D.SALE_QTY*P.UNITPRICE,0) AS JUNV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),07,D.SALE_QTY,0) AS JUL,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),07,D.SALE_QTY*P.UNITPRICE,0) AS JULV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),08,D.SALE_QTY,0) AS AUG,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),08,D.SALE_QTY*P.UNITPRICE,0) AS AUGV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),09,D.SALE_QTY,0) AS SEP,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),09,D.SALE_QTY*P.UNITPRICE,0) AS SEPV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),10,D.SALE_QTY,0) AS OCT,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),10,D.SALE_QTY*P.UNITPRICE,0) AS OCTV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),11,D.SALE_QTY,0) AS NOV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),11,D.SALE_QTY*P.UNITPRICE,0) AS NOVV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),12,D.SALE_QTY,0) AS DEC,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),12,D.SALE_QTY*P.UNITPRICE,0) AS DECV
 FROM SALE_DETAIL D,SALE_MASTER M,CUSTOMERS C,REGION R,PRODUCTS P
  WHERE M.TRANSNO=D.TRANSNO
    AND M.CUSTOMERID=C.CUSTOMERID
    AND TRUNC(D.TRANSDATE) BETWEEN &F_DATE AND &T_DATE
    -- AND TO_CHAR(D.TRANSDATE,'YYYY') =&F_DATE 
    AND D.COMPANY_ID=NVL(&COMPID,D.COMPANY_ID)
    --AND M.CUSTOMERID=NVL(&CUSTID,M.CUSTOMERID)
AND C.REGIONID=R.REGIONID
AND D.COMPANY_ID=P.COMPANY_ID
AND D.PRODUCTID=P.PRODUCTID
--AND D.PRODUCTID = NVL(:PROID,D.PRODUCTID)

UNION ALL


SELECT TO_CHAR(D.TRANSDATE,'YYYY') AS FY,M.CUSTOMERID,C.ORGNAME,C.ADDRESS,R.REGIONNAME,D.COMPPORD,D.COMPANY_ID,D.PRODUCTID,C.NOTE,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),01,SALE_QTY,0) AS JAN,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),01,D.SALE_QTY*P.UNITPRICE,0)*-1 AS JANV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),02,D.SALE_QTY,0) AS FEB,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),02,D.SALE_QTY*P.UNITPRICE,0)*-1 AS FEBV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),03,D.SALE_QTY,0) AS MAR,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),03,D.SALE_QTY*P.UNITPRICE,0)*-1 AS MARV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),04,D.SALE_QTY,0) AS APR,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),04,D.SALE_QTY*P.UNITPRICE,0)*-1 AS APRV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),05,D.SALE_QTY,0) AS MAY,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),05,D.SALE_QTY*D.UNIT_PRICE,0)*-1 AS MAYV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),06,D.SALE_QTY,0) AS JUN,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),06,D.SALE_QTY*P.UNITPRICE,0)*-1 AS JUNV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),07,D.SALE_QTY,0) AS JUL,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),07,D.SALE_QTY*P.UNITPRICE,0)*-1 AS JULV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),08,D.SALE_QTY,0) AS AUG,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),08,D.SALE_QTY*P.UNITPRICE,0)*-1 AS AUGV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),09,D.SALE_QTY,0) AS SEP,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),09,D.SALE_QTY*P.UNITPRICE,0)*-1 AS SEPV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),10,D.SALE_QTY,0) AS OCT,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),10,D.SALE_QTY*P.UNITPRICE,0)*-1 AS OCTV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),11,D.SALE_QTY,0) AS NOV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),11,D.SALE_QTY*P.UNITPRICE,0)*-1 AS NOVV,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),12,D.SALE_QTY,0) AS DEC,
DECODE(TO_CHAR(D.TRANSDATE,'MM'),12,D.SALE_QTY*P.UNITPRICE,0)*-1 AS DECV
 FROM RETURN_DETAIL D,RETURN_MASTER M,CUSTOMERS C,REGION R,PRODUCTS P
  WHERE M.TRANSNO=D.TRANSNO
    AND M.CUSTOMERID=C.CUSTOMERID
    AND TRUNC(D.TRANSDATE) BETWEEN &F_DATE AND &T_DATE
    -- AND TO_CHAR(D.TRANSDATE,'YYYY') =&F_DATE 
    AND D.COMPANY_ID=NVL(&COMPID,D.COMPANY_ID)
    --AND M.CUSTOMERID=NVL(&CUSTID,M.CUSTOMERID)
AND C.REGIONID=R.REGIONID
AND D.COMPANY_ID=P.COMPANY_ID
AND D.PRODUCTID=P.PRODUCTID
--AND D.PRODUCTID = NVL(:PROID,D.PRODUCTID)


)
 GROUP BY FY,CUSTOMERID,ORGNAME,ADDRESS,ADDRESS,REGIONNAME,COMPPORD,COMPANY_ID,PRODUCTID,NOTE),

 COMP AS ( SELECT  C.COMPANY_ID,C.COMPANY_ID||' - '||C.COMPANY_NAME COMPANY_NAME,G.GROUPID,G.GROUPNAME,P.PRODUCTID,P.PRODNAME
            FROM COMPANY C,PRODUCTS P,COMPGROUPS G
                WHERE C.COMPANY_ID=P.COMPANY_ID
                  AND P.COMPANY_ID=G.COMPNAY_ID
                   AND P.GROUPID=G.GROUPID
                   AND NVL(P.MAXALLOW,0)=1
     )
SELECT CUSTOMERID,NOTE,CUSTOMERNAME,ORGNAME,ADDRESS,REGIONNAME,COMPANY_NAME
 ,SUM(JANV2017) AS JANV2017,SUM(JANV2018) AS JANV2018,SUM(FEBV2017) AS FEBV2017,SUM(FEBV2018) AS FEBV2018
 ,SUM(MARV2017) AS MARV2017,SUM(MARV2018) AS MARV2018,SUM(APRV2017) AS APRV2017,SUM(APRV2018) AS APRV2018
 ,SUM(MAYV2017) AS MAYV2017,SUM(MAYV2018) AS MAYV2018,SUM(JUNV2017) AS JUNV2017,SUM(JUNV2018) AS JUNV2018
 ,SUM(JULV2017) AS JULV2017,SUM(JULV2018) AS JULV2018,SUM(AUGV2017) AS AUGV2017,SUM(AUGV2018) AS AUGV2018,
 SUM(SEPV2017) AS SEPV2017,SUM(SEPV2018) AS SEPV2018,SUM(OCTV2017) AS OCTV2017,SUM(OCTV2018) AS OCTV2018,
 SUM(NOVV2017) AS NOVV2017,SUM(NOVV2018) AS NOVV2018,SUM(DECV2017) AS DECV2017,SUM(DECV2018) AS DECV2018
 FROM(
  SELECT S.FY,S.CUSTOMERID,S.NOTE,S.CUSTOMERNAME,S.ORGNAME,ADDRESS,S.REGIONNAME,C.COMPANY_NAME
 ,SUM(S.JANV) AS JANV2017,0 AS JANV2018,SUM(S.FEBV) AS FEBV2017,0 AS FEBV2018
 ,SUM(S.MARV) AS MARV2017,0 AS MARV2018,SUM(S.APRV) AS APRV2017,0 AS APRV2018
 ,SUM(S.MAYV) AS MAYV2017,0 AS MAYV2018,SUM(S.JUNV) AS JUNV2017,0 AS JUNV2018
 ,SUM(S.JULV) AS JULV2017,0 AS JULV2018,SUM(S.AUGV) AS AUGV2017,0 AS AUGV2018,
 SUM(S.SEPV) AS SEPV2017,0 AS SEPV2018,SUM(S.OCTV) AS OCTV2017,0 AS OCTV2018,
 SUM(S.NOVV) AS NOVV2017,0 AS NOVV2018,SUM(S.DECV) AS DECV2017,0 AS DECV2018
 FROM SAL S,COMP C
   WHERE S.COMPANY_ID=C.COMPANY_ID
     AND S.PRODUCTID=C.PRODUCTID 
     AND S.FY='2017'
  ----  AND C.GROUPID = NVL(:GRPID,C.GROUPID) 
GROUP BY S.FY,S.CUSTOMERID,S.NOTE,S.CUSTOMERNAME,S.ORGNAME,C.COMPANY_NAME,ADDRESS,REGIONNAME
-----2018
UNION ALL
 SELECT S.FY,S.CUSTOMERID,S.NOTE,S.CUSTOMERNAME,S.ORGNAME,ADDRESS,S.REGIONNAME,C.COMPANY_NAME
 ,0 AS JANV2017,SUM(S.JANV) AS JANV2018,0 AS FEBV2017,SUM(S.FEBV) AS FEBV2018
 ,0 AS MARV2017,SUM(S.MARV) AS MARV2018,0 AS APRV2017,SUM(S.APRV) AS APRV2018
 ,0 AS MAYV2017,SUM(S.MAYV) AS MAYV2018,0 AS JUNV2017,SUM(S.JUNV) AS JUNV2018
 ,0 AS JULV2017,SUM(S.JULV) AS JULV2018,0 AS AUGV2017,SUM(S.AUGV) AS AUGV2018
 ,0 AS SEPV2017,SUM(S.SEPV) AS SEPV2018,0 AS OCTV2017,SUM(S.OCTV) AS OCTV2018
 ,0 AS NOVV2017,SUM(S.NOVV) AS NOVV2018,0 AS DECV2017,SUM(S.DECV) AS DECV2018
 FROM SAL S,COMP C
   WHERE S.COMPANY_ID=C.COMPANY_ID
     AND S.PRODUCTID=C.PRODUCTID 
     AND S.FY='2018'
  ----  AND C.GROUPID = NVL(:GRPID,C.GROUPID) 
GROUP BY S.FY,S.CUSTOMERID,S.NOTE,S.CUSTOMERNAME,S.ORGNAME,C.COMPANY_NAME,ADDRESS,REGIONNAME
)GROUP BY CUSTOMERID,NOTE,CUSTOMERNAME,ORGNAME,ADDRESS,REGIONNAME,COMPANY_NAME
ORDER BY 1);
